require: rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - "spec/**/**.*"

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
