require: rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - "spec/**/**.*"

Metrics/MethodLength:
  Max: 15

# TODO: re-enable once PR approved
# Style/MethodCallWithArgsParentheses:
#   AllowParenthesesInChaining: false
#   Enabled: true

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NoExpectationExample:
  AllowedPatterns:
    - stub_request
